# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 23:36
from __future__ import unicode_literals

import MHacks.models
from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=60)),
                ('info', models.TextField(default='')),
                ('broadcast_at', models.DateTimeField()),
                ('category', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(63)])),
                ('approved', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('is_high_school', models.BooleanField()),
                ('school', models.CharField(max_length=255)),
                ('major', models.CharField(default='', max_length=255)),
                ('grad_year', models.DateField()),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('non-binary', 'Non Binary'), ('none', 'Prefer not to answer')], max_length=16)),
                ('race', models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('native', 'American Indian or Alaskan Native'), ('asian', 'Asian or Pacific Islander'), ('hispanic', 'Hispanic'), ('none', 'Prefer not to answer')], max_length=16)),
                ('github', models.URLField()),
                ('devpost', models.URLField()),
                ('personal_page', models.URLField()),
                ('resume', models.FileField(upload_to=b'')),
                ('cortex', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web_dev', 'Web Dev'), ('vr', 'Virtual/Augmented Reality'), ('game_dev', 'Game Development'), ('hardware', 'Hardware')], max_length=16), size=None)),
                ('passionate', models.TextField()),
                ('coolest_thing', models.TextField()),
                ('other_info', models.TextField()),
                ('num_hackathons', models.IntegerField(default=0)),
                ('hack_link', models.URLField()),
                ('hack_explanation', models.TextField()),
                ('mentoring', models.BooleanField(default=False)),
                ('submitted', models.BooleanField(default=False)),
                ('score', models.FloatField()),
                ('reimbursement', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=60)),
                ('info', models.TextField(default='')),
                ('start', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('category', models.IntegerField(choices=[(0, 'Logistics'), (1, 'Social'), (2, 'Food'), (3, 'Tech Talk'), (4, 'Other')])),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=60)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('token', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('is_apns', models.BooleanField()),
                ('preferences', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MHacksUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
            },
            managers=[
                ('objects', MHacks.models.MHacksUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='locations',
            field=models.ManyToManyField(to='MHacks.Location'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
