# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 21:07
from __future__ import unicode_literals

from django.db import migrations


def create_groups(apps, schema_editor):
    group_model = apps.get_model('auth', model_name='group')
    from MHacks.globals import groups
    group_model.objects.bulk_create(map(lambda g: group_model(name=g), groups.ALL))
    # TODO: Eventually add in permissions


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(code=create_groups)
    ]
