# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-15 06:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0002_auto_20160814_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='can_pay',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[(b'other', b'Other'), (b'hhh', b'He/Him/His'), (b'shh', b'She/Her/Hers'), (b'ttt', b'They/Them/Theirs')], default='none', max_length=16),
        ),
        migrations.AlterField(
            model_name='application',
            name='race',
            field=models.CharField(choices=[(b'other', b'Other'), (b'none', b'Prefer not to answer'), (b'white', b'White'), (b'black', b'Black'), (b'native', b'American Indian or Alaskan Native'), (b'asian', b'Asian or Pacific Islander'), (b'hispanic', b'Hispanic')], default='none', max_length=16),
        ),
    ]
