# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-08 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0003_auto_20160807_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='personal_page',
            new_name='personal_website',
        ),
    ]
