# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-15 19:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0003_auto_20160814_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='can_pay',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0.0)]),
        ),
        migrations.AlterField(
            model_name='application',
            name='from_state',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='application',
            name='major',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='num_hackathons',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0, message='You went to negative hackathons? Weird...')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='race',
            field=models.CharField(default='', max_length=32),
        ),
    ]
