# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-09 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0004_auto_20160807_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='grad_year',
            new_name='grad_date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='hack_explanation',
        ),
        migrations.RemoveField(
            model_name='application',
            name='hack_link',
        ),
        migrations.AddField(
            model_name='application',
            name='from_city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='from_state',
            field=models.CharField(choices=[(b'AL', b'AL'), (b'AK', b'AK'), (b'AZ', b'AZ'), (b'AR', b'AR'), (b'CA', b'CA'), (b'CO', b'CO'), (b'CT', b'CT'), (b'DE', b'DE'), (b'DC', b'DC'), (b'FL', b'FL'), (b'GA', b'GA'), (b'HI', b'HI'), (b'ID', b'ID'), (b'IL', b'IL'), (b'IN', b'IN'), (b'IA', b'IA'), (b'KS', b'KS'), (b'KY', b'KY'), (b'LA', b'LA'), (b'ME', b'ME'), (b'MT', b'MT'), (b'NE', b'NE'), (b'NV', b'NV'), (b'NH', b'NH'), (b'NJ', b'NJ'), (b'NM', b'NM'), (b'NY', b'NY'), (b'NC', b'NC'), (b'ND', b'ND'), (b'OH', b'OH'), (b'OK', b'OK'), (b'OR', b'OR'), (b'MD', b'MD'), (b'MA', b'MA'), (b'MI', b'MI'), (b'MN', b'MN'), (b'MS', b'MS'), (b'MO', b'MO'), (b'PA', b'PA'), (b'RI', b'RI'), (b'SC', b'SC'), (b'SD', b'SD'), (b'TN', b'TN'), (b'TX', b'TX'), (b'UT', b'UT'), (b'VT', b'VT'), (b'VA', b'VA'), (b'WA', b'WA'), (b'WV', b'WV'), (b'WI', b'WI'), (b'WY', b'WY')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='application',
            name='needs_reimbursement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='reimbursement',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
