# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-15 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0004_auto_20160815_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_international',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_high_school',
            field=models.BooleanField(default=False),
        ),
    ]
