# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 06:24
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0005_auto_20160808_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cortex',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(b'ios', b'iOS'), (b'android', b'Android'), (b'web_dev', b'Web Dev'), (b'vr', b'Virtual/Augmented Reality'), (b'game_dev', b'Game Development'), (b'hardware', b'Hardware')], default='', max_length=16), size=6),
        ),
        migrations.AlterField(
            model_name='application',
            name='from_state',
            field=models.CharField(choices=[(b'Other', b'Other'), (b'AL', b'AL'), (b'AK', b'AK'), (b'AZ', b'AZ'), (b'AR', b'AR'), (b'CA', b'CA'), (b'CO', b'CO'), (b'CT', b'CT'), (b'DE', b'DE'), (b'DC', b'DC'), (b'FL', b'FL'), (b'GA', b'GA'), (b'HI', b'HI'), (b'ID', b'ID'), (b'IL', b'IL'), (b'IN', b'IN'), (b'IA', b'IA'), (b'KS', b'KS'), (b'KY', b'KY'), (b'LA', b'LA'), (b'ME', b'ME'), (b'MT', b'MT'), (b'NE', b'NE'), (b'NV', b'NV'), (b'NH', b'NH'), (b'NJ', b'NJ'), (b'NM', b'NM'), (b'NY', b'NY'), (b'NC', b'NC'), (b'ND', b'ND'), (b'OH', b'OH'), (b'OK', b'OK'), (b'OR', b'OR'), (b'MD', b'MD'), (b'MA', b'MA'), (b'MI', b'MI'), (b'MN', b'MN'), (b'MS', b'MS'), (b'MO', b'MO'), (b'PA', b'PA'), (b'RI', b'RI'), (b'SC', b'SC'), (b'SD', b'SD'), (b'TN', b'TN'), (b'TX', b'TX'), (b'UT', b'UT'), (b'VT', b'VT'), (b'VA', b'VA'), (b'WA', b'WA'), (b'WV', b'WV'), (b'WI', b'WI'), (b'WY', b'WY')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[(b'none', b'Prefer not to answer'), (b'm', b'Male'), (b'f', b'Female'), (b'non-binary', b'Non Binary')], default='none', max_length=16),
        ),
        migrations.AlterField(
            model_name='application',
            name='race',
            field=models.CharField(choices=[(b'none', b'Prefer not to answer'), (b'white', b'White'), (b'black', b'Black'), (b'native', b'American Indian or Alaskan Native'), (b'asian', b'Asian or Pacific Islander'), (b'hispanic', b'Hispanic')], default='none', max_length=16),
        ),
    ]
