# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0006_auto_20160809_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='can_pay',
            field=models.FloatField(default=0),
        ),
    ]
