# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 22:25
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0007_application_can_pay'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mhacksuser',
            options={'default_permissions': (), 'verbose_name': 'User'},
        ),
        migrations.AlterField(
            model_name='application',
            name='cortex',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[(b'ios', b'iOS'), (b'android', b'Android'), (b'web_dev', b'Web Dev'), (b'vr', b'Virtual/Augmented Reality'), (b'game_dev', b'Game Development'), (b'hardware', b'Hardware')], default='', max_length=16), size=6),
        ),
    ]
