# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-16 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0008_auto_20160815_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(max_length=10485760, upload_to=b''),
        ),
    ]
