# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-22 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0009_auto_20160816_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='decision',
            field=models.CharField(choices=[(b'Accept', b'Accept'), (b'Waitlist', b'Waitlist'), (b'Decline', b'Decline')], default='Decline', max_length=16),
        ),
    ]
