# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-23 07:55
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0011_auto_20160822_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('first_time_mentor', models.BooleanField(default=False)),
                ('what_importance', models.TextField()),
                ('why_mentor', models.TextField()),
                ('mentorship_ideas', models.TextField()),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[(b'HTML/CSS', b'HTML/CSS'), (b'Javascript', b'Javascript'), (b'Java', b'Java'), (b'C/C++', b'C/C++'), (b'PHP', b'PHP'), (b'3D modeling', b'3D modeling'), (b'Breadboards', b'Breadboards'), (b'Sensor electronics', b'Sensor electronics'), (b'Haskell', b'Haskell'), (b'Pebble', b'Pebble'), (b'Swift', b'Swift'), (b'Objective-C', b'Objective-C'), (b'C#', b'C#'), (b'Arduino', b'Arduino'), (b'SPICE', b'SPICE'), (b'Oculus', b'Oculus'), (b'Android', b'Android'), (b'Node.js', b'Node.js'), (b'Ruby', b'Ruby'), (b'Python', b'Python'), (b'Unity', b'Unity'), (b'Raspberry Pi', b'Raspberry Pi'), (b'Hardware design', b'Hardware design'), (b'SQL', b'SQL')], max_length=32), size=24)),
                ('other_skills', models.CharField(blank=True, default='', max_length=255)),
                ('github', models.URLField(blank=True)),
                ('agree_tc', models.BooleanField(default=False)),
                ('submitted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
