# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-23 19:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0012_mentorapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorapplication',
            name='decision',
            field=models.CharField(choices=[(b'Accept', b'Accept'), (b'Waitlist', b'Waitlist'), (b'Decline', b'Decline')], default='Decline', max_length=16),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='reimbursement',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0.0)]),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
