# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-24 19:45
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0014_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('acceptance', models.CharField(choices=[(b'yes', b'HAIL YEAH!'), (b'no', b"No, I can't make it")], max_length=32)),
                ('transportation', models.CharField(choices=[(b'plane', b'Plane \xe2\x9c\x88'), (b'train', b'Train \xf0\x9f\x9a\x84'), (b'bus', b'Bus \xf0\x9f\x9a\x8c'), (b'personal', b'Personal transportation \xf0\x9f\x9a\x98')], max_length=32)),
                ('want_help', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[(b'ios', b'iOS'), (b'android', b'Android'), (b'web_dev', b'Web Dev'), (b'vr', b'Virtual/Augmented Reality'), (b'game_dev', b'Game Development'), (b'hardware', b'Hardware')], max_length=16), blank=True, size=6)),
                ('other_want_help', models.CharField(blank=True, max_length=64)),
                ('can_help', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[(b'ios', b'iOS'), (b'android', b'Android'), (b'web_dev', b'Web Dev'), (b'vr', b'Virtual/Augmented Reality'), (b'game_dev', b'Game Development'), (b'hardware', b'Hardware')], max_length=16), blank=True, size=6)),
                ('other_can_help', models.CharField(blank=True, max_length=64)),
                ('t_shirt_size', models.CharField(choices=[(b'S', b'S'), (b'M', b'M'), (b'L', b'L'), (b'XL', b'XL')], max_length=1)),
                ('dietary_restrictions', models.CharField(blank=True, choices=[(b'Vegan', b'Vegan'), (b'Vegetarian', b'Vegetarian'), (b'Gluten free', b'Gluten free'), (b'Halal', b'Halal'), (b'Kosher', b'Kosher')], max_length=32)),
                ('accommodations', models.TextField(blank=True)),
                ('medical_concerns', models.TextField(blank=True)),
                ('phone_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format:                                                                '+#########'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('degree', models.CharField(choices=[(b'HS Diploma', b'HS Diploma'), (b'Bachelors', b'Bachelors'), (b'Masters', b'Masters'), (b'Doctorate', b'Doctorate')], max_length=16)),
                ('employment', models.CharField(blank=True, choices=[(b'.Net', b'.Net'), (b'Android Development', b'Android Development'), (b'Arduino', b'Arduino'), (b'ASP', b'ASP'), (b'Bash', b'Bash'), (b'C', b'C'), (b'C#', b'C#'), (b'C++', b'C++'), (b'CSS', b'CSS'), (b'Data Testing', b'Data Testing'), (b'Database experience', b'Database experience'), (b'Eclipse', b'Eclipse'), (b'Hadoop', b'Hadoop'), (b'Hive', b'Hive'), (b'HTML', b'HTML'), (b'iOS Development', b'iOS Development'), (b'Java', b'Java'), (b'JavaScript', b'JavaScript'), (b'JUnit', b'JUnit'), (b'LaTeX', b'LaTeX'), (b'LINDO', b'LINDO'), (b'Linux Development', b'Linux Development'), (b'Mac OS X Development', b'Mac OS X Development'), (b'MATLAB', b'MATLAB'), (b'MySQL', b'MySQL'), (b'Node.js', b'Node.js'), (b'Objective C', b'Objective C'), (b'Oozie', b'Oozie'), (b'Perl', b'Perl'), (b'PHP', b'PHP'), (b'Python', b'Python'), (b'R', b'R'), (b'Ruby', b'Ruby'), (b'SASS', b'SASS'), (b'SQL', b'SQL'), (b'Sqoop', b'Sqoop'), (b'Swift', b'Swift'), (b'Visual C++', b'Visual C++'), (b'Web Development', b'Web Development'), (b'Windows Development', b'Windows Development')], max_length=32)),
                ('code_of_conduct', models.BooleanField(default=False)),
                ('waiver_signature', models.CharField(max_length=128)),
                ('mlh_code_of_conduct', models.BooleanField(default=False)),
                ('submitted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
