# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-29 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0015_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
