# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-29 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0016_auto_20160828_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
