# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-29 23:05
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0016_auto_20160829_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='technical_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[(b'.Net', b'.Net'), (b'Android Development', b'Android Development'), (b'Arduino', b'Arduino'), (b'ASP', b'ASP'), (b'Bash', b'Bash'), (b'C', b'C'), (b'C#', b'C#'), (b'C++', b'C++'), (b'CSS', b'CSS'), (b'Data Testing', b'Data Testing'), (b'Database experience', b'Database experience'), (b'Eclipse', b'Eclipse'), (b'Hadoop', b'Hadoop'), (b'Hive', b'Hive'), (b'HTML', b'HTML'), (b'iOS Development', b'iOS Development'), (b'Java', b'Java'), (b'JavaScript', b'JavaScript'), (b'JUnit', b'JUnit'), (b'LaTeX', b'LaTeX'), (b'LINDO', b'LINDO'), (b'Linux Development', b'Linux Development'), (b'Mac OS X Development', b'Mac OS X Development'), (b'MATLAB', b'MATLAB'), (b'MySQL', b'MySQL'), (b'Node.js', b'Node.js'), (b'Objective C', b'Objective C'), (b'Oozie', b'Oozie'), (b'Perl', b'Perl'), (b'PHP', b'PHP'), (b'Python', b'Python'), (b'R', b'R'), (b'Ruby', b'Ruby'), (b'SASS', b'SASS'), (b'SQL', b'SQL'), (b'Sqoop', b'Sqoop'), (b'Swift', b'Swift'), (b'Visual C++', b'Visual C++'), (b'Web Development', b'Web Development'), (b'Windows Development', b'Windows Development')], max_length=32), blank=True, size=40),
        ),
    ]
