# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-29 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0017_auto_20160829_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='anything_else',
            field=models.TextField(blank=True),
        ),
    ]
