# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0018_registration_anything_else'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
