# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-01 17:49
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0019_auto_20160830_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='acceptance',
            field=models.CharField(choices=[(b'yes', b'HAIL YEAH! \xf0\x9f\x98\x80'), (b'no', b"No, I can't make it \xf0\x9f\x98\xad")], max_length=32),
        ),
        migrations.AlterField(
            model_name='registration',
            name='can_help',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[(b'ios', b'iOS'), (b'android', b'Android'), (b'web_dev', b'Web Dev'), (b'vr', b'Virtual/Augmented Reality'), (b'game_dev', b'Game Development'), (b'hardware', b'Hardware')], max_length=16), blank=True, null=True, size=6),
        ),
    ]
