# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-07 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0022_auto_20160902_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='employment',
            field=models.CharField(choices=[(b'Internship (I am graduating in December 2017 or later)', b'Internship (I am graduating in December 2017 or later)'), (b'Full\xc2\xadTime Employment (I am graduating prior to June 2017)', b'Full\xc2\xadTime Employment (I am graduating prior to June 2017)'), (b'Part\xc2\xadTime Employment while in school (Co-op)', b'Part\xc2\xadTime Employment while in school (Co-op)'), (b'Not Interested', b'Not Interested')], max_length=64),
        ),
    ]
