# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-07 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0023_auto_20160907_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='employment',
            field=models.CharField(choices=[(b'internship', b'Internship (I am graduating in December 2017 or later)'), (b'full time', b'Full\xc2\xadTime Employment (I am graduating prior to June 2017)'), (b'part time', b'Part\xc2\xadTime Employment while in school (Co-op)'), (b'none', b'Not Interested')], max_length=64),
        ),
    ]
