# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0025_auto_20160907_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='mentor',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
