# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0026_auto_20160907_2343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushToken',
        ),
    ]
