# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-22 06:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0029_auto_20160919_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanevent',
            name='custom_verification',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='scanevent',
            name='expiry_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='scanevent',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='scan_event_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
