# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-22 06:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0030_auto_20160922_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanEventUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='scanevent',
            name='users',
        ),
        migrations.AddField(
            model_name='scaneventuser',
            name='scan_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MHacks.ScanEvent'),
        ),
        migrations.AddField(
            model_name='scaneventuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scanevent',
            name='scanned_users',
            field=models.ManyToManyField(blank=True, related_name='scan_event_users', through='MHacks.ScanEventUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
