# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-29 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0031_auto_20160922_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=60)),
                ('index', models.IntegerField(unique=True)),
                ('image', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
        migrations.AddField(
            model_name='location',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MHacks.Floor'),
        ),
    ]
