# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-29 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0032_auto_20160929_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='MHacks.Floor'),
        ),
    ]
