# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-30 23:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0034_auto_20160929_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanevent',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanevent',
            name='number_of_allowable_scans',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
    ]
