# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-02 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0035_auto_20160930_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='aspect_ratio',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='floor',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='floor',
            name='offset_fraction',
            field=models.FloatField(default=1.0),
        ),
    ]
