# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-03 02:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0036_auto_20161002_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.IntegerField(choices=[(0, 'General'), (1, 'Logistics'), (2, 'Food'), (3, 'Learn'), (4, 'Social')]),
        ),
    ]
