# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-02 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0039_auto_20170202_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorapplication',
            name='has_user_design_experience',
            field=models.BooleanField(default=False),
        ),
    ]
