# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-02 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0040_mentorapplication_has_user_design_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='has_side_projects',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='linkedin',
            field=models.URLField(default='https://linkedin.com/in/username'),
        ),
        migrations.AddField(
            model_name='application',
            name='num_cs_courses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='num_ux_courses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='other_links',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='application',
            name='devpost',
            field=models.URLField(default='https://devpost.com/username'),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='application',
            name='github',
            field=models.URLField(default='https://github.com/username'),
        ),
        migrations.AlterField(
            model_name='application',
            name='personal_website',
            field=models.URLField(default=''),
        ),
    ]
