# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-08 17:44
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0041_auto_20170202_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cortex',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[(b'ios', b'iOS'), (b'android', b'Android'), (b'web_dev', b'Web Dev'), (b'vr', b'Virtual/Augmented Reality'), (b'game_dev', b'Game Development'), (b'hardware', b'Hardware'), (b'ui_ux', b'Design'), (b'ai_ml', b'Artificial Intelligence/Machine Learning')], default='', max_length=16), size=8),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('', 'Gender'), ('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-Binary'), ('other', 'Other')], default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='application',
            name='race',
            field=models.CharField(choices=[('', 'Race'), ('american_indian_or_alaskan_native', 'American Indian or Alaskan Native'), ('asian_or_pacific_islander', 'Asian or Pacific Islander'), ('black', 'Black'), ('hispanic', 'Hispanic'), ('white', 'White'), ('other', 'Other')], default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='registration',
            name='can_help',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[(b'ios', b'iOS'), (b'android', b'Android'), (b'web_dev', b'Web Dev'), (b'vr', b'Virtual/Augmented Reality'), (b'game_dev', b'Game Development'), (b'hardware', b'Hardware'), (b'ui_ux', b'Design'), (b'ai_ml', b'Artificial Intelligence/Machine Learning')], max_length=16), blank=True, null=True, size=8),
        ),
        migrations.AlterField(
            model_name='registration',
            name='want_help',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[(b'ios', b'iOS'), (b'android', b'Android'), (b'web_dev', b'Web Dev'), (b'vr', b'Virtual/Augmented Reality'), (b'game_dev', b'Game Development'), (b'hardware', b'Hardware'), (b'ui_ux', b'Design'), (b'ai_ml', b'Artificial Intelligence/Machine Learning')], max_length=16), blank=True, size=8),
        ),
    ]
