# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-14 17:13
from __future__ import unicode_literals

import MHacks.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0044_auto_20170208_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(max_length=10485760, upload_to=MHacks.utils.change_resume_filename),
        ),
    ]
