# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-15 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0045_auto_20170214_1113'),
        ('MHacks', '0045_auto_20170212_2112'),
    ]

    operations = [
    ]
