# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-14 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHacks', '0046_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='nw_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='floor',
            name='nw_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='floor',
            name='se_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='floor',
            name='se_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='floor',
            name='aspect_ratio',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='floor',
            name='offset_fraction',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='employment',
            field=models.CharField(choices=[(b'internship', b'Internship'), (b'full time', b'Full Time Employment'), (b'part time', b'Part Time Employment while in school (Co-op)'), (b'none', b'Not Interested')], max_length=64),
        ),
    ]
